version: "1.0"

name: tc # traffic control

services:
  emqx:
    image: emqx:latest
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    networks:
      - tcntw
  
  rabbitmq:
    image: rabbitmq:management
    healthcheck:
      test: rabbitmq-plugins -q is_enabled rabbitmq_management_agent
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - tcntw

  ekuiper:
    image: lfedge/ekuiper:latest
    ports:
      - 9081:9081
      - 127.0.0.1:20498:20498
    restart: unless-stopped
    user: root
    volumes:
      - ekuiper_data:/kuiper/data
      - ekuiper_log:/kuiper/log
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://emqx:1883"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__IGNORECASE: "false"
    depends_on:
      emqx:
        condition: service_healthy
    networks:
      - tcntw

  ekuiper_manager:
    image: emqx/ekuiper-manager:latest
    ports:
      - 9082:9082
    restart: unless-stopped
    environment:
      DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081"
    networks:
      - tcntw

  influxdb:
    image: influxdb:latest
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - tcntw
    ports:
      - 8086:8086
    volumes:
      - influxdb_storage:/var/lib/influxdb

  monitoring:
    build:
      context: .
      dockerfile: ./Microservices/MonitoringService/Dockerfile
    depends_on:
      emqx:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - tcntw

  restapi:
    build:
      context: .
      dockerfile: ./Microservices/RestAPI/Dockerfile
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - tcntw
    ports: 
      - 80:80


networks:
  tcntw:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_log:
  ekuiper_data:
  ekuiper_log:
  influxdb_storage: